#!/usr/bin/perl
use warnings;
use strict;

############################
## Pseudocode for Project ##
############################


#Ask user for reference sequence(list filetype?)
#Ask user for bisulfite treated sequence
print "Enter the Reference Seqeunce:\n ";
my $reference =<STDIN> ;
print "Enter the Bisulfite Sequence: \n";
my $BiSulSeq = <STDIN>;


open (REFERENCE,$reference) || die "The refernece  file cannot be opened";
my $seqA = <REFERENCE>;
close (REFERENCE);

open (BISUL,$BiSulSeq) || die "This Bisulfite file cannot be opened";
my $seqB = <BISUL>;
close (BISUL);


#store files in variable
#prepare files
	#remove whitespace
	#remove newlines
	#join into one string
	#explode string into an array
my $seq1=$seqA;
my $seq2=$seqB;
$seq1 =~ tr/acgt/ACGT/;
$seq2 =~ tr/acgt/ACGT/;

print $seq1;
print $seq2;

my @seq1 = split('',$seq1);
my @seq2 = split('',$seq2);
####Looking for areas of CC matching
my @CCmatches;
my $k=0;

for (my $i=0; $i < scalar (@seq1); $i++)
{
    if ($seq1[$i] eq "C" && $seq2[$i] eq "C")
    {$CCmatches[$k] = $i;$k++;
    }
}

my $CC = join (',',@CCmatches);
print "\n";
print $CC;
print "\n";
####Looking for regoins with TC matches
my @TCmatches;
my $z=0;

for (my $y=0; $y < scalar(@seq1);$y++)
{
    if ($seq1[$y] eq "C" && $seq2[$y] eq "T")
    {$TCmatches[$z] = $y; $z++;
    }
}
my $TC = join (',',@TCmatches);
print $TC;
print "\n";



#Search for CG regions
	#foreach /C/ {
	#	if( /GC/ | /CG/){}
	# remove duplicated regions (i.e. GCG)
	# 	else {}
	# }
	
#Store and report position of CG regions (file output)

##Compare arrays using Perl 5.1's Smartmatch Operator

#Find CG regions on reference genome array
	#store Cs in an array that has empty elements for locations where there is not a C
		#for example:
			#reference-   AAATCCAGCTTTTACGAAA
			#array of Cs- ********C*****C****, where * indicates whitespace
	#Match location of CG regions from reference genome to the bisulfite treated genome
		#clear out non-matching regions (?)
		#for example:
			#reference genome		AAATCCAGCTTTTACGAAA
			#reference C regions	********C*****C****
			#bisulfite genome		AAATTTAGTTTTTACGAAA
			#matched bisulfite		********T*****C****
			
	
	#Report Results of comparison in text file format? Spreadsheet?
	
			
exit;






